### ISSUE TITLE
Soccer rule is incorrect

### ISSUE THREAD

**Issue by iltenahmet** [DigiLogicLabs/OpenSourceSports#2]
The rule `7. No tackling or physical contact is allowed between players, except for the goalkeeper when inside the penalty area.` for soccer is incorrect. Physical contact is an important part of the game and it is allowed depending on the type of contact. For example, shoulder to shoulder contact is often allowed, however, direct pushing or tackling from behind is not.

**Comment by DigiLogicLabs** [comment]
Hi @iltenahmet 

Thank you for bringing this to our attention. We appreciate your engagement with the OpenSourceSports repository and recognize the importance of having the most accurate and up-to-date rules for each sport.

You are absolutely correct that certain types of physical contact are indeed a part of soccer and are permitted within the rules of the game and we understand that the current wording may not fully capture the nuances of acceptable physical contact in soccer.

We are in the process of reviewing and updating our rules to ensure they are consistent with the most current official regulations. If you have a specific set of updated rules or a URL where the official rules are listed, please feel free to share it. This will help us in revising the rules to be as accurate and useful as possible.

Additionally, we are structuring the repository to empower users like you to propose changes directly. You are welcome to create a pull request with the changes you believe should be made.

Thank you once again for your contribution. 

Best,
@DigiLogicLabs
